#!/bin/bash
#LMEs for INPUT and OUTPUT delay maps. 

for direction in inny outy; do
    if [[ $direction == inny ]]; then
        stats="nzmedian nzmean stdev max nzcount 95 99"
    elif [[ $direction == outy ]]; then
        stats="mean median stdev max"
    fi
    for stat in $stats; do
        3dLME -prefix /data/gcooper/movie_delay/LMEs/LME_"$stat"_"$direction".nii.gz \
        -resid /data/gcooper/movie_delay/LMEs/LME_"$stat"_"$direction"_resids.nii.gz \
        -model 'movie*moviepart+age+gender' \
        -jobs 8 \
        -ranEff '~1' \
        -qVars "age,cogfluid,negaffect" \
        -qVarCenters "26.81,53.43,52.8" \
        -num_glt 7 \
        -SS_type 3 \
        -gltLabel 1 'all' -gltCode 1 'moviepart : 0.333*beginning 0.333*middle 0.333*end' \
        -gltLabel 2 'BvM' -gltCode 2 'moviepart : 1*beginning -1*middle' \
        -gltLabel 3 'BvE' -gltCode 3 'moviepart : 1*beginning -1*end' \
        -gltLabel 4 'MvE' -gltCode 4 'moviepart : 1*middle -1*end' \
        -gltLabel 5 'Beg' -gltCode 5 'moviepart : 1*beginning' \
        -gltLabel 6 'Mid' -gltCode 6 'moviepart : 1*middle' \
        -gltLabel 7 'End' -gltCode 7 'moviepart : 1*end' \
        -dataTable \
        Subj movie moviepart age gender cogfluid negaffect monoling InputFile \
        1 500days beginning 23 M 99 65 yes /data/gcooper/movie_delay/delay_mapping/sub-1/wholebrain_delay_maps/beginning/pos/inny/1_beginning_pos_"$direction"_"$stat".nii.gz \
        2 500days beginning 25 F 53.43 54 no /data/gcooper/movie_delay/delay_mapping/sub-2/wholebrain_delay_maps/beginning/pos/inny/2_beginning_pos_"$direction"_"$stat".nii.gz \
        3 500days beginning 23 M 59 46 yes /data/gcooper/movie_delay/delay_mapping/sub-3/wholebrain_delay_maps/beginning/pos/inny/3_beginning_pos_"$direction"_"$stat".nii.gz \
        4 500days beginning 23 M 21 55 yes /data/gcooper/movie_delay/delay_mapping/sub-4/wholebrain_delay_maps/beginning/pos/inny/4_beginning_pos_"$direction"_"$stat".nii.gz \
        5 500days beginning 22 F 87 63 yes /data/gcooper/movie_delay/delay_mapping/sub-5/wholebrain_delay_maps/beginning/pos/inny/5_beginning_pos_"$direction"_"$stat".nii.gz \
        6 500days beginning 25 M 18 49 no /data/gcooper/movie_delay/delay_mapping/sub-6/wholebrain_delay_maps/beginning/pos/inny/6_beginning_pos_"$direction"_"$stat".nii.gz \
        7 500days beginning 23 F 22 53 yes /data/gcooper/movie_delay/delay_mapping/sub-7/wholebrain_delay_maps/beginning/pos/inny/7_beginning_pos_"$direction"_"$stat".nii.gz \
        8 500days beginning 23 F 74 43 yes /data/gcooper/movie_delay/delay_mapping/sub-8/wholebrain_delay_maps/beginning/pos/inny/8_beginning_pos_"$direction"_"$stat".nii.gz \
        9 500days beginning 28 F 99 35 no /data/gcooper/movie_delay/delay_mapping/sub-9/wholebrain_delay_maps/beginning/pos/inny/9_beginning_pos_"$direction"_"$stat".nii.gz \
        10 500days beginning 31 M 78 50 yes /data/gcooper/movie_delay/delay_mapping/sub-10/wholebrain_delay_maps/beginning/pos/inny/10_beginning_pos_"$direction"_"$stat".nii.gz \
        11 500days beginning 20 F 24 27 yes /data/gcooper/movie_delay/delay_mapping/sub-11/wholebrain_delay_maps/beginning/pos/inny/11_beginning_pos_"$direction"_"$stat".nii.gz \
        12 500days beginning 19 M 80 55 yes /data/gcooper/movie_delay/delay_mapping/sub-12/wholebrain_delay_maps/beginning/pos/inny/12_beginning_pos_"$direction"_"$stat".nii.gz \
        13 500days beginning 19 F 77 60 yes /data/gcooper/movie_delay/delay_mapping/sub-13/wholebrain_delay_maps/beginning/pos/inny/13_beginning_pos_"$direction"_"$stat".nii.gz \
        14 500days beginning 38 M 48 59 yes /data/gcooper/movie_delay/delay_mapping/sub-14/wholebrain_delay_maps/beginning/pos/inny/14_beginning_pos_"$direction"_"$stat".nii.gz \
        15 500days beginning 22 F 37 68 yes /data/gcooper/movie_delay/delay_mapping/sub-15/wholebrain_delay_maps/beginning/pos/inny/15_beginning_pos_"$direction"_"$stat".nii.gz \
        16 500days beginning 50 F 1 73 yes /data/gcooper/movie_delay/delay_mapping/sub-16/wholebrain_delay_maps/beginning/pos/inny/16_beginning_pos_"$direction"_"$stat".nii.gz \
        17 500days beginning 22 M 50 49 yes /data/gcooper/movie_delay/delay_mapping/sub-17/wholebrain_delay_maps/beginning/pos/inny/17_beginning_pos_"$direction"_"$stat".nii.gz \
        18 500days beginning 53 M 75 25 yes /data/gcooper/movie_delay/delay_mapping/sub-18/wholebrain_delay_maps/beginning/pos/inny/18_beginning_pos_"$direction"_"$stat".nii.gz \
        19 500days beginning 22 F 76 43 yes /data/gcooper/movie_delay/delay_mapping/sub-19/wholebrain_delay_maps/beginning/pos/inny/19_beginning_pos_"$direction"_"$stat".nii.gz \
        20 500days beginning 43 M 79 53 yes /data/gcooper/movie_delay/delay_mapping/sub-20/wholebrain_delay_maps/beginning/pos/inny/20_beginning_pos_"$direction"_"$stat".nii.gz \
        21 Citizenfour beginning 27 M 75 52 yes /data/gcooper/movie_delay/delay_mapping/sub-21/wholebrain_delay_maps/beginning/pos/inny/21_beginning_pos_"$direction"_"$stat".nii.gz \
        22 Citizenfour beginning 23 M 94 46 yes /data/gcooper/movie_delay/delay_mapping/sub-22/wholebrain_delay_maps/beginning/pos/inny/22_beginning_pos_"$direction"_"$stat".nii.gz \
        23 Citizenfour beginning 24 M 53.43 39 yes /data/gcooper/movie_delay/delay_mapping/sub-23/wholebrain_delay_maps/beginning/pos/inny/23_beginning_pos_"$direction"_"$stat".nii.gz \
        24 Citizenfour beginning 22 M 91 44 na /data/gcooper/movie_delay/delay_mapping/sub-24/wholebrain_delay_maps/beginning/pos/inny/24_beginning_pos_"$direction"_"$stat".nii.gz \
        25 Citizenfour beginning 20 F 73 50 yes /data/gcooper/movie_delay/delay_mapping/sub-25/wholebrain_delay_maps/beginning/pos/inny/25_beginning_pos_"$direction"_"$stat".nii.gz \
        26 Citizenfour beginning 26 F 95 29 yes /data/gcooper/movie_delay/delay_mapping/sub-26/wholebrain_delay_maps/beginning/pos/inny/26_beginning_pos_"$direction"_"$stat".nii.gz \
        27 Citizenfour beginning 21 M 2 51 yes /data/gcooper/movie_delay/delay_mapping/sub-27/wholebrain_delay_maps/beginning/pos/inny/27_beginning_pos_"$direction"_"$stat".nii.gz \
        28 Citizenfour beginning 20 F 13 53 yes /data/gcooper/movie_delay/delay_mapping/sub-28/wholebrain_delay_maps/beginning/pos/inny/28_beginning_pos_"$direction"_"$stat".nii.gz \
        29 Citizenfour beginning 19 F 99 55 yes /data/gcooper/movie_delay/delay_mapping/sub-29/wholebrain_delay_maps/beginning/pos/inny/29_beginning_pos_"$direction"_"$stat".nii.gz \
        30 Citizenfour beginning 20 M 18 56 yes /data/gcooper/movie_delay/delay_mapping/sub-30/wholebrain_delay_maps/beginning/pos/inny/30_beginning_pos_"$direction"_"$stat".nii.gz \
        31 Citizenfour beginning 30 M 60 35 no /data/gcooper/movie_delay/delay_mapping/sub-31/wholebrain_delay_maps/beginning/pos/inny/31_beginning_pos_"$direction"_"$stat".nii.gz \
        32 Citizenfour beginning 35 M 1 54 no /data/gcooper/movie_delay/delay_mapping/sub-32/wholebrain_delay_maps/beginning/pos/inny/32_beginning_pos_"$direction"_"$stat".nii.gz \
        33 Citizenfour beginning 58 M 49 71 yes /data/gcooper/movie_delay/delay_mapping/sub-33/wholebrain_delay_maps/beginning/pos/inny/33_beginning_pos_"$direction"_"$stat".nii.gz \
        34 Citizenfour beginning 46 F 6 55 yes /data/gcooper/movie_delay/delay_mapping/sub-34/wholebrain_delay_maps/beginning/pos/inny/34_beginning_pos_"$direction"_"$stat".nii.gz \
        35 Citizenfour beginning 19 F 96 57 yes /data/gcooper/movie_delay/delay_mapping/sub-35/wholebrain_delay_maps/beginning/pos/inny/35_beginning_pos_"$direction"_"$stat".nii.gz \
        36 Citizenfour beginning 34 F 99 63 yes /data/gcooper/movie_delay/delay_mapping/sub-36/wholebrain_delay_maps/beginning/pos/inny/36_beginning_pos_"$direction"_"$stat".nii.gz \
        37 Citizenfour beginning 21 F 9 62 no /data/gcooper/movie_delay/delay_mapping/sub-37/wholebrain_delay_maps/beginning/pos/inny/37_beginning_pos_"$direction"_"$stat".nii.gz \
        38 Citizenfour beginning 21 F 33 50 yes /data/gcooper/movie_delay/delay_mapping/sub-38/wholebrain_delay_maps/beginning/pos/inny/38_beginning_pos_"$direction"_"$stat".nii.gz \
        39 usualsuspects beginning 21 F 98 68 yes /data/gcooper/movie_delay/delay_mapping/sub-39/wholebrain_delay_maps/beginning/pos/inny/39_beginning_pos_"$direction"_"$stat".nii.gz \
        40 usualsuspects beginning 25 F 61 57 yes /data/gcooper/movie_delay/delay_mapping/sub-40/wholebrain_delay_maps/beginning/pos/inny/40_beginning_pos_"$direction"_"$stat".nii.gz \
        41 usualsuspects beginning 23 F 57 46 yes /data/gcooper/movie_delay/delay_mapping/sub-41/wholebrain_delay_maps/beginning/pos/inny/41_beginning_pos_"$direction"_"$stat".nii.gz \
        42 usualsuspects beginning 20 M 2 60 yes /data/gcooper/movie_delay/delay_mapping/sub-42/wholebrain_delay_maps/beginning/pos/inny/42_beginning_pos_"$direction"_"$stat".nii.gz \
        43 usualsuspects beginning 25 M 98 56 yes /data/gcooper/movie_delay/delay_mapping/sub-43/wholebrain_delay_maps/beginning/pos/inny/43_beginning_pos_"$direction"_"$stat".nii.gz \
        44 usualsuspects beginning 25 M 16 40 no /data/gcooper/movie_delay/delay_mapping/sub-44/wholebrain_delay_maps/beginning/pos/inny/44_beginning_pos_"$direction"_"$stat".nii.gz \
        45 pulpfiction beginning 19 F 22 66 no /data/gcooper/movie_delay/delay_mapping/sub-45/wholebrain_delay_maps/beginning/pos/inny/45_beginning_pos_"$direction"_"$stat".nii.gz \
        46 pulpfiction beginning 31 F 44 61 no /data/gcooper/movie_delay/delay_mapping/sub-46/wholebrain_delay_maps/beginning/pos/inny/46_beginning_pos_"$direction"_"$stat".nii.gz \
        47 pulpfiction beginning 21 F 89 51 yes /data/gcooper/movie_delay/delay_mapping/sub-47/wholebrain_delay_maps/beginning/pos/inny/47_beginning_pos_"$direction"_"$stat".nii.gz \
        48 pulpfiction beginning 22 M 73 60 yes /data/gcooper/movie_delay/delay_mapping/sub-48/wholebrain_delay_maps/beginning/pos/inny/48_beginning_pos_"$direction"_"$stat".nii.gz \
        49 pulpfiction beginning 19 M 7 60 yes /data/gcooper/movie_delay/delay_mapping/sub-49/wholebrain_delay_maps/beginning/pos/inny/49_beginning_pos_"$direction"_"$stat".nii.gz \
        50 pulpfiction beginning 24 M 71 48 yes /data/gcooper/movie_delay/delay_mapping/sub-50/wholebrain_delay_maps/beginning/pos/inny/50_beginning_pos_"$direction"_"$stat".nii.gz \
        51 shawshank beginning 22 M 27 36 no /data/gcooper/movie_delay/delay_mapping/sub-51/wholebrain_delay_maps/beginning/pos/inny/51_beginning_pos_"$direction"_"$stat".nii.gz \
        52 shawshank beginning 30 M 90 49 yes /data/gcooper/movie_delay/delay_mapping/sub-52/wholebrain_delay_maps/beginning/pos/inny/52_beginning_pos_"$direction"_"$stat".nii.gz \
        53 shawshank beginning 20 F 89 58 yes /data/gcooper/movie_delay/delay_mapping/sub-53/wholebrain_delay_maps/beginning/pos/inny/53_beginning_pos_"$direction"_"$stat".nii.gz \
        54 shawshank beginning 19 F 91 55 no /data/gcooper/movie_delay/delay_mapping/sub-54/wholebrain_delay_maps/beginning/pos/inny/54_beginning_pos_"$direction"_"$stat".nii.gz \
        55 shawshank beginning 19 F 18 45 no /data/gcooper/movie_delay/delay_mapping/sub-55/wholebrain_delay_maps/beginning/pos/inny/55_beginning_pos_"$direction"_"$stat".nii.gz \
        56 shawshank beginning 23 M 93 57 yes /data/gcooper/movie_delay/delay_mapping/sub-56/wholebrain_delay_maps/beginning/pos/inny/56_beginning_pos_"$direction"_"$stat".nii.gz \
        57 prestige beginning 23 F 53.43 37 yes /data/gcooper/movie_delay/delay_mapping/sub-57/wholebrain_delay_maps/beginning/pos/inny/57_beginning_pos_"$direction"_"$stat".nii.gz \
        58 prestige beginning 50 M 46 54 yes /data/gcooper/movie_delay/delay_mapping/sub-58/wholebrain_delay_maps/beginning/pos/inny/58_beginning_pos_"$direction"_"$stat".nii.gz \
        59 prestige beginning 58 M 62 56 yes /data/gcooper/movie_delay/delay_mapping/sub-59/wholebrain_delay_maps/beginning/pos/inny/59_beginning_pos_"$direction"_"$stat".nii.gz \
        60 prestige beginning 33 M 99 60 yes /data/gcooper/movie_delay/delay_mapping/sub-60/wholebrain_delay_maps/beginning/pos/inny/60_beginning_pos_"$direction"_"$stat".nii.gz \
        61 prestige beginning 26.81 F 53.43 47 yes /data/gcooper/movie_delay/delay_mapping/sub-61/wholebrain_delay_maps/beginning/pos/inny/61_beginning_pos_"$direction"_"$stat".nii.gz \
        62 prestige beginning 21 F 97 56 yes /data/gcooper/movie_delay/delay_mapping/sub-62/wholebrain_delay_maps/beginning/pos/inny/62_beginning_pos_"$direction"_"$stat".nii.gz \
        63 backtofuture beginning 22 M 1 64 yes /data/gcooper/movie_delay/delay_mapping/sub-63/wholebrain_delay_maps/beginning/pos/inny/63_beginning_pos_"$direction"_"$stat".nii.gz \
        64 backtofuture beginning 18 F 23 57 no /data/gcooper/movie_delay/delay_mapping/sub-64/wholebrain_delay_maps/beginning/pos/inny/64_beginning_pos_"$direction"_"$stat".nii.gz \
        65 backtofuture beginning 21 F 90 56 yes /data/gcooper/movie_delay/delay_mapping/sub-65/wholebrain_delay_maps/beginning/pos/inny/65_beginning_pos_"$direction"_"$stat".nii.gz \
        66 backtofuture beginning 24 M 2 68 no /data/gcooper/movie_delay/delay_mapping/sub-66/wholebrain_delay_maps/beginning/pos/inny/66_beginning_pos_"$direction"_"$stat".nii.gz \
        67 backtofuture beginning 23 F 83 33 yes /data/gcooper/movie_delay/delay_mapping/sub-67/wholebrain_delay_maps/beginning/pos/inny/67_beginning_pos_"$direction"_"$stat".nii.gz \
        68 backtofuture beginning 25 M 39 68 yes /data/gcooper/movie_delay/delay_mapping/sub-68/wholebrain_delay_maps/beginning/pos/inny/68_beginning_pos_"$direction"_"$stat".nii.gz \
        69 split beginning 24 F 85 65 yes /data/gcooper/movie_delay/delay_mapping/sub-69/wholebrain_delay_maps/beginning/pos/inny/69_beginning_pos_"$direction"_"$stat".nii.gz \
        70 split beginning 19 F 90 64 no /data/gcooper/movie_delay/delay_mapping/sub-70/wholebrain_delay_maps/beginning/pos/inny/70_beginning_pos_"$direction"_"$stat".nii.gz \
        71 split beginning 25 M 52 62 yes /data/gcooper/movie_delay/delay_mapping/sub-71/wholebrain_delay_maps/beginning/pos/inny/71_beginning_pos_"$direction"_"$stat".nii.gz \
        72 split beginning 20 M 40 63 yes /data/gcooper/movie_delay/delay_mapping/sub-72/wholebrain_delay_maps/beginning/pos/inny/72_beginning_pos_"$direction"_"$stat".nii.gz \
        73 split beginning 24 M 11 49 yes /data/gcooper/movie_delay/delay_mapping/sub-73/wholebrain_delay_maps/beginning/pos/inny/73_beginning_pos_"$direction"_"$stat".nii.gz \
        74 split beginning 24 F 38 42 yes /data/gcooper/movie_delay/delay_mapping/sub-74/wholebrain_delay_maps/beginning/pos/inny/74_beginning_pos_"$direction"_"$stat".nii.gz \
        75 littlemisssunshine beginning 45 F 99 54 yes /data/gcooper/movie_delay/delay_mapping/sub-75/wholebrain_delay_maps/beginning/pos/inny/75_beginning_pos_"$direction"_"$stat".nii.gz \
        76 littlemisssunshine beginning 20 M 2 56 no /data/gcooper/movie_delay/delay_mapping/sub-76/wholebrain_delay_maps/beginning/pos/inny/76_beginning_pos_"$direction"_"$stat".nii.gz \
        77 littlemisssunshine beginning 29 M 2 29 yes /data/gcooper/movie_delay/delay_mapping/sub-77/wholebrain_delay_maps/beginning/pos/inny/77_beginning_pos_"$direction"_"$stat".nii.gz \
        78 littlemisssunshine beginning 45 M 85 58 yes /data/gcooper/movie_delay/delay_mapping/sub-78/wholebrain_delay_maps/beginning/pos/inny/78_beginning_pos_"$direction"_"$stat".nii.gz \
        79 littlemisssunshine beginning 20 F 65 63 no /data/gcooper/movie_delay/delay_mapping/sub-79/wholebrain_delay_maps/beginning/pos/inny/79_beginning_pos_"$direction"_"$stat".nii.gz \
        80 littlemisssunshine beginning 55 M 21 54 yes /data/gcooper/movie_delay/delay_mapping/sub-80/wholebrain_delay_maps/beginning/pos/inny/80_beginning_pos_"$direction"_"$stat".nii.gz \
        81 12years beginning 31 M 1 54 yes /data/gcooper/movie_delay/delay_mapping/sub-81/wholebrain_delay_maps/beginning/pos/inny/81_beginning_pos_"$direction"_"$stat".nii.gz \
        82 12years beginning 50 M 15 35 no /data/gcooper/movie_delay/delay_mapping/sub-82/wholebrain_delay_maps/beginning/pos/inny/82_beginning_pos_"$direction"_"$stat".nii.gz \
        83 12years beginning 18 F 25 45 no /data/gcooper/movie_delay/delay_mapping/sub-83/wholebrain_delay_maps/beginning/pos/inny/83_beginning_pos_"$direction"_"$stat".nii.gz \
        84 12years beginning 22 F 60 64 yes /data/gcooper/movie_delay/delay_mapping/sub-84/wholebrain_delay_maps/beginning/pos/inny/84_beginning_pos_"$direction"_"$stat".nii.gz \
        85 12years beginning 23 F 22 54 yes /data/gcooper/movie_delay/delay_mapping/sub-85/wholebrain_delay_maps/beginning/pos/inny/85_beginning_pos_"$direction"_"$stat".nii.gz \
        86 12years beginning 19 M 63 53 no /data/gcooper/movie_delay/delay_mapping/sub-86/wholebrain_delay_maps/beginning/pos/inny/86_beginning_pos_"$direction"_"$stat".nii.gz \
        1 500days middle 23 M 99 65 yes /data/gcooper/movie_delay/delay_mapping/sub-1/wholebrain_delay_maps/middle/pos/inny/1_middle_pos_"$direction"_"$stat".nii.gz \
        2 500days middle 25 F 53.43 54 no /data/gcooper/movie_delay/delay_mapping/sub-2/wholebrain_delay_maps/middle/pos/inny/2_middle_pos_"$direction"_"$stat".nii.gz \
        3 500days middle 23 M 59 46 yes /data/gcooper/movie_delay/delay_mapping/sub-3/wholebrain_delay_maps/middle/pos/inny/3_middle_pos_"$direction"_"$stat".nii.gz \
        4 500days middle 23 M 21 55 yes /data/gcooper/movie_delay/delay_mapping/sub-4/wholebrain_delay_maps/middle/pos/inny/4_middle_pos_"$direction"_"$stat".nii.gz \
        5 500days middle 22 F 87 63 yes /data/gcooper/movie_delay/delay_mapping/sub-5/wholebrain_delay_maps/middle/pos/inny/5_middle_pos_"$direction"_"$stat".nii.gz \
        6 500days middle 25 M 18 49 no /data/gcooper/movie_delay/delay_mapping/sub-6/wholebrain_delay_maps/middle/pos/inny/6_middle_pos_"$direction"_"$stat".nii.gz \
        7 500days middle 23 F 22 53 yes /data/gcooper/movie_delay/delay_mapping/sub-7/wholebrain_delay_maps/middle/pos/inny/7_middle_pos_"$direction"_"$stat".nii.gz \
        8 500days middle 23 F 74 43 yes /data/gcooper/movie_delay/delay_mapping/sub-8/wholebrain_delay_maps/middle/pos/inny/8_middle_pos_"$direction"_"$stat".nii.gz \
        9 500days middle 28 F 99 35 no /data/gcooper/movie_delay/delay_mapping/sub-9/wholebrain_delay_maps/middle/pos/inny/9_middle_pos_"$direction"_"$stat".nii.gz \
        10 500days middle 31 M 78 50 yes /data/gcooper/movie_delay/delay_mapping/sub-10/wholebrain_delay_maps/middle/pos/inny/10_middle_pos_"$direction"_"$stat".nii.gz \
        11 500days middle 20 F 24 27 yes /data/gcooper/movie_delay/delay_mapping/sub-11/wholebrain_delay_maps/middle/pos/inny/11_middle_pos_"$direction"_"$stat".nii.gz \
        12 500days middle 19 M 80 55 yes /data/gcooper/movie_delay/delay_mapping/sub-12/wholebrain_delay_maps/middle/pos/inny/12_middle_pos_"$direction"_"$stat".nii.gz \
        13 500days middle 19 F 77 60 yes /data/gcooper/movie_delay/delay_mapping/sub-13/wholebrain_delay_maps/middle/pos/inny/13_middle_pos_"$direction"_"$stat".nii.gz \
        14 500days middle 38 M 48 59 yes /data/gcooper/movie_delay/delay_mapping/sub-14/wholebrain_delay_maps/middle/pos/inny/14_middle_pos_"$direction"_"$stat".nii.gz \
        15 500days middle 22 F 37 68 yes /data/gcooper/movie_delay/delay_mapping/sub-15/wholebrain_delay_maps/middle/pos/inny/15_middle_pos_"$direction"_"$stat".nii.gz \
        16 500days middle 50 F 1 73 yes /data/gcooper/movie_delay/delay_mapping/sub-16/wholebrain_delay_maps/middle/pos/inny/16_middle_pos_"$direction"_"$stat".nii.gz \
        17 500days middle 22 M 50 49 yes /data/gcooper/movie_delay/delay_mapping/sub-17/wholebrain_delay_maps/middle/pos/inny/17_middle_pos_"$direction"_"$stat".nii.gz \
        18 500days middle 53 M 75 25 yes /data/gcooper/movie_delay/delay_mapping/sub-18/wholebrain_delay_maps/middle/pos/inny/18_middle_pos_"$direction"_"$stat".nii.gz \
        19 500days middle 22 F 76 43 yes /data/gcooper/movie_delay/delay_mapping/sub-19/wholebrain_delay_maps/middle/pos/inny/19_middle_pos_"$direction"_"$stat".nii.gz \
        20 500days middle 43 M 79 53 yes /data/gcooper/movie_delay/delay_mapping/sub-20/wholebrain_delay_maps/middle/pos/inny/20_middle_pos_"$direction"_"$stat".nii.gz \
        21 Citizenfour middle 27 M 75 52 yes /data/gcooper/movie_delay/delay_mapping/sub-21/wholebrain_delay_maps/middle/pos/inny/21_middle_pos_"$direction"_"$stat".nii.gz \
        22 Citizenfour middle 23 M 94 46 yes /data/gcooper/movie_delay/delay_mapping/sub-22/wholebrain_delay_maps/middle/pos/inny/22_middle_pos_"$direction"_"$stat".nii.gz \
        23 Citizenfour middle 24 M 53.43 39 yes /data/gcooper/movie_delay/delay_mapping/sub-23/wholebrain_delay_maps/middle/pos/inny/23_middle_pos_"$direction"_"$stat".nii.gz \
        24 Citizenfour middle 22 M 91 44 na /data/gcooper/movie_delay/delay_mapping/sub-24/wholebrain_delay_maps/middle/pos/inny/24_middle_pos_"$direction"_"$stat".nii.gz \
        25 Citizenfour middle 20 F 73 50 yes /data/gcooper/movie_delay/delay_mapping/sub-25/wholebrain_delay_maps/middle/pos/inny/25_middle_pos_"$direction"_"$stat".nii.gz \
        26 Citizenfour middle 26 F 95 29 yes /data/gcooper/movie_delay/delay_mapping/sub-26/wholebrain_delay_maps/middle/pos/inny/26_middle_pos_"$direction"_"$stat".nii.gz \
        27 Citizenfour middle 21 M 2 51 yes /data/gcooper/movie_delay/delay_mapping/sub-27/wholebrain_delay_maps/middle/pos/inny/27_middle_pos_"$direction"_"$stat".nii.gz \
        28 Citizenfour middle 20 F 13 53 yes /data/gcooper/movie_delay/delay_mapping/sub-28/wholebrain_delay_maps/middle/pos/inny/28_middle_pos_"$direction"_"$stat".nii.gz \
        29 Citizenfour middle 19 F 99 55 yes /data/gcooper/movie_delay/delay_mapping/sub-29/wholebrain_delay_maps/middle/pos/inny/29_middle_pos_"$direction"_"$stat".nii.gz \
        30 Citizenfour middle 20 M 18 56 yes /data/gcooper/movie_delay/delay_mapping/sub-30/wholebrain_delay_maps/middle/pos/inny/30_middle_pos_"$direction"_"$stat".nii.gz \
        31 Citizenfour middle 30 M 60 35 no /data/gcooper/movie_delay/delay_mapping/sub-31/wholebrain_delay_maps/middle/pos/inny/31_middle_pos_"$direction"_"$stat".nii.gz \
        32 Citizenfour middle 35 M 1 54 no /data/gcooper/movie_delay/delay_mapping/sub-32/wholebrain_delay_maps/middle/pos/inny/32_middle_pos_"$direction"_"$stat".nii.gz \
        33 Citizenfour middle 58 M 49 71 yes /data/gcooper/movie_delay/delay_mapping/sub-33/wholebrain_delay_maps/middle/pos/inny/33_middle_pos_"$direction"_"$stat".nii.gz \
        34 Citizenfour middle 46 F 6 55 yes /data/gcooper/movie_delay/delay_mapping/sub-34/wholebrain_delay_maps/middle/pos/inny/34_middle_pos_"$direction"_"$stat".nii.gz \
        35 Citizenfour middle 19 F 96 57 yes /data/gcooper/movie_delay/delay_mapping/sub-35/wholebrain_delay_maps/middle/pos/inny/35_middle_pos_"$direction"_"$stat".nii.gz \
        36 Citizenfour middle 34 F 99 63 yes /data/gcooper/movie_delay/delay_mapping/sub-36/wholebrain_delay_maps/middle/pos/inny/36_middle_pos_"$direction"_"$stat".nii.gz \
        37 Citizenfour middle 21 F 9 62 no /data/gcooper/movie_delay/delay_mapping/sub-37/wholebrain_delay_maps/middle/pos/inny/37_middle_pos_"$direction"_"$stat".nii.gz \
        38 Citizenfour middle 21 F 33 50 yes /data/gcooper/movie_delay/delay_mapping/sub-38/wholebrain_delay_maps/middle/pos/inny/38_middle_pos_"$direction"_"$stat".nii.gz \
        39 usualsuspects middle 21 F 98 68 yes /data/gcooper/movie_delay/delay_mapping/sub-39/wholebrain_delay_maps/middle/pos/inny/39_middle_pos_"$direction"_"$stat".nii.gz \
        40 usualsuspects middle 25 F 61 57 yes /data/gcooper/movie_delay/delay_mapping/sub-40/wholebrain_delay_maps/middle/pos/inny/40_middle_pos_"$direction"_"$stat".nii.gz \
        41 usualsuspects middle 23 F 57 46 yes /data/gcooper/movie_delay/delay_mapping/sub-41/wholebrain_delay_maps/middle/pos/inny/41_middle_pos_"$direction"_"$stat".nii.gz \
        42 usualsuspects middle 20 M 2 60 yes /data/gcooper/movie_delay/delay_mapping/sub-42/wholebrain_delay_maps/middle/pos/inny/42_middle_pos_"$direction"_"$stat".nii.gz \
        43 usualsuspects middle 25 M 98 56 yes /data/gcooper/movie_delay/delay_mapping/sub-43/wholebrain_delay_maps/middle/pos/inny/43_middle_pos_"$direction"_"$stat".nii.gz \
        44 usualsuspects middle 25 M 16 40 no /data/gcooper/movie_delay/delay_mapping/sub-44/wholebrain_delay_maps/middle/pos/inny/44_middle_pos_"$direction"_"$stat".nii.gz \
        45 pulpfiction middle 19 F 22 66 no /data/gcooper/movie_delay/delay_mapping/sub-45/wholebrain_delay_maps/middle/pos/inny/45_middle_pos_"$direction"_"$stat".nii.gz \
        46 pulpfiction middle 31 F 44 61 no /data/gcooper/movie_delay/delay_mapping/sub-46/wholebrain_delay_maps/middle/pos/inny/46_middle_pos_"$direction"_"$stat".nii.gz \
        47 pulpfiction middle 21 F 89 51 yes /data/gcooper/movie_delay/delay_mapping/sub-47/wholebrain_delay_maps/middle/pos/inny/47_middle_pos_"$direction"_"$stat".nii.gz \
        48 pulpfiction middle 22 M 73 60 yes /data/gcooper/movie_delay/delay_mapping/sub-48/wholebrain_delay_maps/middle/pos/inny/48_middle_pos_"$direction"_"$stat".nii.gz \
        49 pulpfiction middle 19 M 7 60 yes /data/gcooper/movie_delay/delay_mapping/sub-49/wholebrain_delay_maps/middle/pos/inny/49_middle_pos_"$direction"_"$stat".nii.gz \
        50 pulpfiction middle 24 M 71 48 yes /data/gcooper/movie_delay/delay_mapping/sub-50/wholebrain_delay_maps/middle/pos/inny/50_middle_pos_"$direction"_"$stat".nii.gz \
        51 shawshank middle 22 M 27 36 no /data/gcooper/movie_delay/delay_mapping/sub-51/wholebrain_delay_maps/middle/pos/inny/51_middle_pos_"$direction"_"$stat".nii.gz \
        52 shawshank middle 30 M 90 49 yes /data/gcooper/movie_delay/delay_mapping/sub-52/wholebrain_delay_maps/middle/pos/inny/52_middle_pos_"$direction"_"$stat".nii.gz \
        53 shawshank middle 20 F 89 58 yes /data/gcooper/movie_delay/delay_mapping/sub-53/wholebrain_delay_maps/middle/pos/inny/53_middle_pos_"$direction"_"$stat".nii.gz \
        54 shawshank middle 19 F 91 55 no /data/gcooper/movie_delay/delay_mapping/sub-54/wholebrain_delay_maps/middle/pos/inny/54_middle_pos_"$direction"_"$stat".nii.gz \
        55 shawshank middle 19 F 18 45 no /data/gcooper/movie_delay/delay_mapping/sub-55/wholebrain_delay_maps/middle/pos/inny/55_middle_pos_"$direction"_"$stat".nii.gz \
        56 shawshank middle 23 M 93 57 yes /data/gcooper/movie_delay/delay_mapping/sub-56/wholebrain_delay_maps/middle/pos/inny/56_middle_pos_"$direction"_"$stat".nii.gz \
        57 prestige middle 23 F 53.43 37 yes /data/gcooper/movie_delay/delay_mapping/sub-57/wholebrain_delay_maps/middle/pos/inny/57_middle_pos_"$direction"_"$stat".nii.gz \
        58 prestige middle 50 M 46 54 yes /data/gcooper/movie_delay/delay_mapping/sub-58/wholebrain_delay_maps/middle/pos/inny/58_middle_pos_"$direction"_"$stat".nii.gz \
        59 prestige middle 58 M 62 56 yes /data/gcooper/movie_delay/delay_mapping/sub-59/wholebrain_delay_maps/middle/pos/inny/59_middle_pos_"$direction"_"$stat".nii.gz \
        60 prestige middle 33 M 99 60 yes /data/gcooper/movie_delay/delay_mapping/sub-60/wholebrain_delay_maps/middle/pos/inny/60_middle_pos_"$direction"_"$stat".nii.gz \
        61 prestige middle 26.83 F 53.43 47 yes /data/gcooper/movie_delay/delay_mapping/sub-61/wholebrain_delay_maps/middle/pos/inny/61_middle_pos_"$direction"_"$stat".nii.gz \
        62 prestige middle 21 F 97 56 yes /data/gcooper/movie_delay/delay_mapping/sub-62/wholebrain_delay_maps/middle/pos/inny/62_middle_pos_"$direction"_"$stat".nii.gz \
        63 backtofuture middle 22 M 1 64 yes /data/gcooper/movie_delay/delay_mapping/sub-63/wholebrain_delay_maps/middle/pos/inny/63_middle_pos_"$direction"_"$stat".nii.gz \
        64 backtofuture middle 18 F 23 57 no /data/gcooper/movie_delay/delay_mapping/sub-64/wholebrain_delay_maps/middle/pos/inny/64_middle_pos_"$direction"_"$stat".nii.gz \
        65 backtofuture middle 21 F 90 56 yes /data/gcooper/movie_delay/delay_mapping/sub-65/wholebrain_delay_maps/middle/pos/inny/65_middle_pos_"$direction"_"$stat".nii.gz \
        66 backtofuture middle 24 M 2 68 no /data/gcooper/movie_delay/delay_mapping/sub-66/wholebrain_delay_maps/middle/pos/inny/66_middle_pos_"$direction"_"$stat".nii.gz \
        67 backtofuture middle 23 F 83 33 yes /data/gcooper/movie_delay/delay_mapping/sub-67/wholebrain_delay_maps/middle/pos/inny/67_middle_pos_"$direction"_"$stat".nii.gz \
        68 backtofuture middle 25 M 39 68 yes /data/gcooper/movie_delay/delay_mapping/sub-68/wholebrain_delay_maps/middle/pos/inny/68_middle_pos_"$direction"_"$stat".nii.gz \
        69 split middle 24 F 85 65 yes /data/gcooper/movie_delay/delay_mapping/sub-69/wholebrain_delay_maps/middle/pos/inny/69_middle_pos_"$direction"_"$stat".nii.gz \
        70 split middle 19 F 90 64 no /data/gcooper/movie_delay/delay_mapping/sub-70/wholebrain_delay_maps/middle/pos/inny/70_middle_pos_"$direction"_"$stat".nii.gz \
        71 split middle 25 M 52 62 yes /data/gcooper/movie_delay/delay_mapping/sub-71/wholebrain_delay_maps/middle/pos/inny/71_middle_pos_"$direction"_"$stat".nii.gz \
        72 split middle 20 M 40 63 yes /data/gcooper/movie_delay/delay_mapping/sub-72/wholebrain_delay_maps/middle/pos/inny/72_middle_pos_"$direction"_"$stat".nii.gz \
        73 split middle 24 M 11 49 yes /data/gcooper/movie_delay/delay_mapping/sub-73/wholebrain_delay_maps/middle/pos/inny/73_middle_pos_"$direction"_"$stat".nii.gz \
        74 split middle 24 F 38 42 yes /data/gcooper/movie_delay/delay_mapping/sub-74/wholebrain_delay_maps/middle/pos/inny/74_middle_pos_"$direction"_"$stat".nii.gz \
        75 littlemisssunshine middle 45 F 99 54 yes /data/gcooper/movie_delay/delay_mapping/sub-75/wholebrain_delay_maps/middle/pos/inny/75_middle_pos_"$direction"_"$stat".nii.gz \
        76 littlemisssunshine middle 20 M 2 56 no /data/gcooper/movie_delay/delay_mapping/sub-76/wholebrain_delay_maps/middle/pos/inny/76_middle_pos_"$direction"_"$stat".nii.gz \
        77 littlemisssunshine middle 29 M 2 29 yes /data/gcooper/movie_delay/delay_mapping/sub-77/wholebrain_delay_maps/middle/pos/inny/77_middle_pos_"$direction"_"$stat".nii.gz \
        78 littlemisssunshine middle 45 M 85 58 yes /data/gcooper/movie_delay/delay_mapping/sub-78/wholebrain_delay_maps/middle/pos/inny/78_middle_pos_"$direction"_"$stat".nii.gz \
        79 littlemisssunshine middle 20 F 65 63 no /data/gcooper/movie_delay/delay_mapping/sub-79/wholebrain_delay_maps/middle/pos/inny/79_middle_pos_"$direction"_"$stat".nii.gz \
        80 littlemisssunshine middle 55 M 21 54 yes /data/gcooper/movie_delay/delay_mapping/sub-80/wholebrain_delay_maps/middle/pos/inny/80_middle_pos_"$direction"_"$stat".nii.gz \
        81 12years middle 31 M 1 54 yes /data/gcooper/movie_delay/delay_mapping/sub-81/wholebrain_delay_maps/middle/pos/inny/81_middle_pos_"$direction"_"$stat".nii.gz \
        82 12years middle 50 M 15 35 no /data/gcooper/movie_delay/delay_mapping/sub-82/wholebrain_delay_maps/middle/pos/inny/82_middle_pos_"$direction"_"$stat".nii.gz \
        83 12years middle 18 F 25 45 no /data/gcooper/movie_delay/delay_mapping/sub-83/wholebrain_delay_maps/middle/pos/inny/83_middle_pos_"$direction"_"$stat".nii.gz \
        84 12years middle 22 F 60 64 yes /data/gcooper/movie_delay/delay_mapping/sub-84/wholebrain_delay_maps/middle/pos/inny/84_middle_pos_"$direction"_"$stat".nii.gz \
        85 12years middle 23 F 22 54 yes /data/gcooper/movie_delay/delay_mapping/sub-85/wholebrain_delay_maps/middle/pos/inny/85_middle_pos_"$direction"_"$stat".nii.gz \
        86 12years middle 19 M 63 53 no /data/gcooper/movie_delay/delay_mapping/sub-86/wholebrain_delay_maps/middle/pos/inny/86_middle_pos_"$direction"_"$stat".nii.gz \
        1 500days end 23 M 99 65 yes /data/gcooper/movie_delay/delay_mapping/sub-1/wholebrain_delay_maps/end/pos/inny/1_end_pos_"$direction"_"$stat".nii.gz \
        2 500days end 25 F 53.43 54 no /data/gcooper/movie_delay/delay_mapping/sub-2/wholebrain_delay_maps/end/pos/inny/2_end_pos_"$direction"_"$stat".nii.gz \
        3 500days end 23 M 59 46 yes /data/gcooper/movie_delay/delay_mapping/sub-3/wholebrain_delay_maps/end/pos/inny/3_end_pos_"$direction"_"$stat".nii.gz \
        4 500days end 23 M 21 55 yes /data/gcooper/movie_delay/delay_mapping/sub-4/wholebrain_delay_maps/end/pos/inny/4_end_pos_"$direction"_"$stat".nii.gz \
        5 500days end 22 F 87 63 yes /data/gcooper/movie_delay/delay_mapping/sub-5/wholebrain_delay_maps/end/pos/inny/5_end_pos_"$direction"_"$stat".nii.gz \
        6 500days end 25 M 18 49 no /data/gcooper/movie_delay/delay_mapping/sub-6/wholebrain_delay_maps/end/pos/inny/6_end_pos_"$direction"_"$stat".nii.gz \
        7 500days end 23 F 22 53 yes /data/gcooper/movie_delay/delay_mapping/sub-7/wholebrain_delay_maps/end/pos/inny/7_end_pos_"$direction"_"$stat".nii.gz \
        8 500days end 23 F 74 43 yes /data/gcooper/movie_delay/delay_mapping/sub-8/wholebrain_delay_maps/end/pos/inny/8_end_pos_"$direction"_"$stat".nii.gz \
        9 500days end 28 F 99 35 no /data/gcooper/movie_delay/delay_mapping/sub-9/wholebrain_delay_maps/end/pos/inny/9_end_pos_"$direction"_"$stat".nii.gz \
        10 500days end 31 M 78 50 yes /data/gcooper/movie_delay/delay_mapping/sub-10/wholebrain_delay_maps/end/pos/inny/10_end_pos_"$direction"_"$stat".nii.gz \
        11 500days end 20 F 24 27 yes /data/gcooper/movie_delay/delay_mapping/sub-11/wholebrain_delay_maps/end/pos/inny/11_end_pos_"$direction"_"$stat".nii.gz \
        12 500days end 19 M 80 55 yes /data/gcooper/movie_delay/delay_mapping/sub-12/wholebrain_delay_maps/end/pos/inny/12_end_pos_"$direction"_"$stat".nii.gz \
        13 500days end 19 F 77 60 yes /data/gcooper/movie_delay/delay_mapping/sub-13/wholebrain_delay_maps/end/pos/inny/13_end_pos_"$direction"_"$stat".nii.gz \
        14 500days end 38 M 48 59 yes /data/gcooper/movie_delay/delay_mapping/sub-14/wholebrain_delay_maps/end/pos/inny/14_end_pos_"$direction"_"$stat".nii.gz \
        15 500days end 22 F 37 68 yes /data/gcooper/movie_delay/delay_mapping/sub-15/wholebrain_delay_maps/end/pos/inny/15_end_pos_"$direction"_"$stat".nii.gz \
        16 500days end 50 F 1 73 yes /data/gcooper/movie_delay/delay_mapping/sub-16/wholebrain_delay_maps/end/pos/inny/16_end_pos_"$direction"_"$stat".nii.gz \
        17 500days end 22 M 50 49 yes /data/gcooper/movie_delay/delay_mapping/sub-17/wholebrain_delay_maps/end/pos/inny/17_end_pos_"$direction"_"$stat".nii.gz \
        18 500days end 53 M 75 25 yes /data/gcooper/movie_delay/delay_mapping/sub-18/wholebrain_delay_maps/end/pos/inny/18_end_pos_"$direction"_"$stat".nii.gz \
        19 500days end 22 F 76 43 yes /data/gcooper/movie_delay/delay_mapping/sub-19/wholebrain_delay_maps/end/pos/inny/19_end_pos_"$direction"_"$stat".nii.gz \
        20 500days end 43 M 79 53 yes /data/gcooper/movie_delay/delay_mapping/sub-20/wholebrain_delay_maps/end/pos/inny/20_end_pos_"$direction"_"$stat".nii.gz \
        21 Citizenfour end 27 M 75 52 yes /data/gcooper/movie_delay/delay_mapping/sub-21/wholebrain_delay_maps/end/pos/inny/21_end_pos_"$direction"_"$stat".nii.gz \
        22 Citizenfour end 23 M 94 46 yes /data/gcooper/movie_delay/delay_mapping/sub-22/wholebrain_delay_maps/end/pos/inny/22_end_pos_"$direction"_"$stat".nii.gz \
        23 Citizenfour end 24 M 53.43 39 yes /data/gcooper/movie_delay/delay_mapping/sub-23/wholebrain_delay_maps/end/pos/inny/23_end_pos_"$direction"_"$stat".nii.gz \
        24 Citizenfour end 22 M 91 44 na /data/gcooper/movie_delay/delay_mapping/sub-24/wholebrain_delay_maps/end/pos/inny/24_end_pos_"$direction"_"$stat".nii.gz \
        25 Citizenfour end 20 F 73 50 yes /data/gcooper/movie_delay/delay_mapping/sub-25/wholebrain_delay_maps/end/pos/inny/25_end_pos_"$direction"_"$stat".nii.gz \
        26 Citizenfour end 26 F 95 29 yes /data/gcooper/movie_delay/delay_mapping/sub-26/wholebrain_delay_maps/end/pos/inny/26_end_pos_"$direction"_"$stat".nii.gz \
        27 Citizenfour end 21 M 2 51 yes /data/gcooper/movie_delay/delay_mapping/sub-27/wholebrain_delay_maps/end/pos/inny/27_end_pos_"$direction"_"$stat".nii.gz \
        28 Citizenfour end 20 F 13 53 yes /data/gcooper/movie_delay/delay_mapping/sub-28/wholebrain_delay_maps/end/pos/inny/28_end_pos_"$direction"_"$stat".nii.gz \
        29 Citizenfour end 19 F 99 55 yes /data/gcooper/movie_delay/delay_mapping/sub-29/wholebrain_delay_maps/end/pos/inny/29_end_pos_"$direction"_"$stat".nii.gz \
        30 Citizenfour end 20 M 18 56 yes /data/gcooper/movie_delay/delay_mapping/sub-30/wholebrain_delay_maps/end/pos/inny/30_end_pos_"$direction"_"$stat".nii.gz \
        31 Citizenfour end 30 M 60 35 no /data/gcooper/movie_delay/delay_mapping/sub-31/wholebrain_delay_maps/end/pos/inny/31_end_pos_"$direction"_"$stat".nii.gz \
        32 Citizenfour end 35 M 1 54 no /data/gcooper/movie_delay/delay_mapping/sub-32/wholebrain_delay_maps/end/pos/inny/32_end_pos_"$direction"_"$stat".nii.gz \
        33 Citizenfour end 58 M 49 71 yes /data/gcooper/movie_delay/delay_mapping/sub-33/wholebrain_delay_maps/end/pos/inny/33_end_pos_"$direction"_"$stat".nii.gz \
        34 Citizenfour end 46 F 6 55 yes /data/gcooper/movie_delay/delay_mapping/sub-34/wholebrain_delay_maps/end/pos/inny/34_end_pos_"$direction"_"$stat".nii.gz \
        35 Citizenfour end 19 F 96 57 yes /data/gcooper/movie_delay/delay_mapping/sub-35/wholebrain_delay_maps/end/pos/inny/35_end_pos_"$direction"_"$stat".nii.gz \
        36 Citizenfour end 34 F 99 63 yes /data/gcooper/movie_delay/delay_mapping/sub-36/wholebrain_delay_maps/end/pos/inny/36_end_pos_"$direction"_"$stat".nii.gz \
        37 Citizenfour end 21 F 9 62 no /data/gcooper/movie_delay/delay_mapping/sub-37/wholebrain_delay_maps/end/pos/inny/37_end_pos_"$direction"_"$stat".nii.gz \
        38 Citizenfour end 21 F 33 50 yes /data/gcooper/movie_delay/delay_mapping/sub-38/wholebrain_delay_maps/end/pos/inny/38_end_pos_"$direction"_"$stat".nii.gz \
        39 usualsuspects end 21 F 98 68 yes /data/gcooper/movie_delay/delay_mapping/sub-39/wholebrain_delay_maps/end/pos/inny/39_end_pos_"$direction"_"$stat".nii.gz \
        40 usualsuspects end 25 F 61 57 yes /data/gcooper/movie_delay/delay_mapping/sub-40/wholebrain_delay_maps/end/pos/inny/40_end_pos_"$direction"_"$stat".nii.gz \
        41 usualsuspects end 23 F 57 46 yes /data/gcooper/movie_delay/delay_mapping/sub-41/wholebrain_delay_maps/end/pos/inny/41_end_pos_"$direction"_"$stat".nii.gz \
        42 usualsuspects end 20 M 2 60 yes /data/gcooper/movie_delay/delay_mapping/sub-42/wholebrain_delay_maps/end/pos/inny/42_end_pos_"$direction"_"$stat".nii.gz \
        43 usualsuspects end 25 M 98 56 yes /data/gcooper/movie_delay/delay_mapping/sub-43/wholebrain_delay_maps/end/pos/inny/43_end_pos_"$direction"_"$stat".nii.gz \
        44 usualsuspects end 25 M 16 40 no /data/gcooper/movie_delay/delay_mapping/sub-44/wholebrain_delay_maps/end/pos/inny/44_end_pos_"$direction"_"$stat".nii.gz \
        45 pulpfiction end 19 F 22 66 no /data/gcooper/movie_delay/delay_mapping/sub-45/wholebrain_delay_maps/end/pos/inny/45_end_pos_"$direction"_"$stat".nii.gz \
        46 pulpfiction end 31 F 44 61 no /data/gcooper/movie_delay/delay_mapping/sub-46/wholebrain_delay_maps/end/pos/inny/46_end_pos_"$direction"_"$stat".nii.gz \
        47 pulpfiction end 21 F 89 51 yes /data/gcooper/movie_delay/delay_mapping/sub-47/wholebrain_delay_maps/end/pos/inny/47_end_pos_"$direction"_"$stat".nii.gz \
        48 pulpfiction end 22 M 73 60 yes /data/gcooper/movie_delay/delay_mapping/sub-48/wholebrain_delay_maps/end/pos/inny/48_end_pos_"$direction"_"$stat".nii.gz \
        49 pulpfiction end 19 M 7 60 yes /data/gcooper/movie_delay/delay_mapping/sub-49/wholebrain_delay_maps/end/pos/inny/49_end_pos_"$direction"_"$stat".nii.gz \
        50 pulpfiction end 24 M 71 48 yes /data/gcooper/movie_delay/delay_mapping/sub-50/wholebrain_delay_maps/end/pos/inny/50_end_pos_"$direction"_"$stat".nii.gz \
        51 shawshank end 22 M 27 36 no /data/gcooper/movie_delay/delay_mapping/sub-51/wholebrain_delay_maps/end/pos/inny/51_end_pos_"$direction"_"$stat".nii.gz \
        52 shawshank end 30 M 90 49 yes /data/gcooper/movie_delay/delay_mapping/sub-52/wholebrain_delay_maps/end/pos/inny/52_end_pos_"$direction"_"$stat".nii.gz \
        53 shawshank end 20 F 89 58 yes /data/gcooper/movie_delay/delay_mapping/sub-53/wholebrain_delay_maps/end/pos/inny/53_end_pos_"$direction"_"$stat".nii.gz \
        54 shawshank end 19 F 91 55 no /data/gcooper/movie_delay/delay_mapping/sub-54/wholebrain_delay_maps/end/pos/inny/54_end_pos_"$direction"_"$stat".nii.gz \
        55 shawshank end 19 F 18 45 no /data/gcooper/movie_delay/delay_mapping/sub-55/wholebrain_delay_maps/end/pos/inny/55_end_pos_"$direction"_"$stat".nii.gz \
        56 shawshank end 23 M 93 57 yes /data/gcooper/movie_delay/delay_mapping/sub-56/wholebrain_delay_maps/end/pos/inny/56_end_pos_"$direction"_"$stat".nii.gz \
        57 prestige end 23 F 53.43 37 yes /data/gcooper/movie_delay/delay_mapping/sub-57/wholebrain_delay_maps/end/pos/inny/57_end_pos_"$direction"_"$stat".nii.gz \
        58 prestige end 50 M 46 54 yes /data/gcooper/movie_delay/delay_mapping/sub-58/wholebrain_delay_maps/end/pos/inny/58_end_pos_"$direction"_"$stat".nii.gz \
        59 prestige end 58 M 62 56 yes /data/gcooper/movie_delay/delay_mapping/sub-59/wholebrain_delay_maps/end/pos/inny/59_end_pos_"$direction"_"$stat".nii.gz \
        60 prestige end 33 M 99 60 yes /data/gcooper/movie_delay/delay_mapping/sub-60/wholebrain_delay_maps/end/pos/inny/60_end_pos_"$direction"_"$stat".nii.gz \
        61 prestige end 26.81 F 53.43 47 yes /data/gcooper/movie_delay/delay_mapping/sub-61/wholebrain_delay_maps/end/pos/inny/61_end_pos_"$direction"_"$stat".nii.gz \
        62 prestige end 21 F 97 56 yes /data/gcooper/movie_delay/delay_mapping/sub-62/wholebrain_delay_maps/end/pos/inny/62_end_pos_"$direction"_"$stat".nii.gz \
        63 backtofuture end 22 M 1 64 yes /data/gcooper/movie_delay/delay_mapping/sub-63/wholebrain_delay_maps/end/pos/inny/63_end_pos_"$direction"_"$stat".nii.gz \
        64 backtofuture end 18 F 23 57 no /data/gcooper/movie_delay/delay_mapping/sub-64/wholebrain_delay_maps/end/pos/inny/64_end_pos_"$direction"_"$stat".nii.gz \
        65 backtofuture end 21 F 90 56 yes /data/gcooper/movie_delay/delay_mapping/sub-65/wholebrain_delay_maps/end/pos/inny/65_end_pos_"$direction"_"$stat".nii.gz \
        66 backtofuture end 24 M 2 68 no /data/gcooper/movie_delay/delay_mapping/sub-66/wholebrain_delay_maps/end/pos/inny/66_end_pos_"$direction"_"$stat".nii.gz \
        67 backtofuture end 23 F 83 33 yes /data/gcooper/movie_delay/delay_mapping/sub-67/wholebrain_delay_maps/end/pos/inny/67_end_pos_"$direction"_"$stat".nii.gz \
        68 backtofuture end 25 M 39 68 yes /data/gcooper/movie_delay/delay_mapping/sub-68/wholebrain_delay_maps/end/pos/inny/68_end_pos_"$direction"_"$stat".nii.gz \
        69 split end 24 F 85 65 yes /data/gcooper/movie_delay/delay_mapping/sub-69/wholebrain_delay_maps/end/pos/inny/69_end_pos_"$direction"_"$stat".nii.gz \
        70 split end 19 F 90 64 no /data/gcooper/movie_delay/delay_mapping/sub-70/wholebrain_delay_maps/end/pos/inny/70_end_pos_"$direction"_"$stat".nii.gz \
        71 split end 25 M 52 62 yes /data/gcooper/movie_delay/delay_mapping/sub-71/wholebrain_delay_maps/end/pos/inny/71_end_pos_"$direction"_"$stat".nii.gz \
        72 split end 20 M 40 63 yes /data/gcooper/movie_delay/delay_mapping/sub-72/wholebrain_delay_maps/end/pos/inny/72_end_pos_"$direction"_"$stat".nii.gz \
        73 split end 24 M 11 49 yes /data/gcooper/movie_delay/delay_mapping/sub-73/wholebrain_delay_maps/end/pos/inny/73_end_pos_"$direction"_"$stat".nii.gz \
        74 split end 24 F 38 42 yes /data/gcooper/movie_delay/delay_mapping/sub-74/wholebrain_delay_maps/end/pos/inny/74_end_pos_"$direction"_"$stat".nii.gz \
        75 littlemisssunshine end 45 F 99 54 yes /data/gcooper/movie_delay/delay_mapping/sub-75/wholebrain_delay_maps/end/pos/inny/75_end_pos_"$direction"_"$stat".nii.gz \
        76 littlemisssunshine end 20 M 2 56 no /data/gcooper/movie_delay/delay_mapping/sub-76/wholebrain_delay_maps/end/pos/inny/76_end_pos_"$direction"_"$stat".nii.gz \
        77 littlemisssunshine end 29 M 2 29 yes /data/gcooper/movie_delay/delay_mapping/sub-77/wholebrain_delay_maps/end/pos/inny/77_end_pos_"$direction"_"$stat".nii.gz \
        78 littlemisssunshine end 45 M 85 58 yes /data/gcooper/movie_delay/delay_mapping/sub-78/wholebrain_delay_maps/end/pos/inny/78_end_pos_"$direction"_"$stat".nii.gz \
        79 littlemisssunshine end 20 F 65 63 no /data/gcooper/movie_delay/delay_mapping/sub-79/wholebrain_delay_maps/end/pos/inny/79_end_pos_"$direction"_"$stat".nii.gz \
        80 littlemisssunshine end 55 M 21 54 yes /data/gcooper/movie_delay/delay_mapping/sub-80/wholebrain_delay_maps/end/pos/inny/80_end_pos_"$direction"_"$stat".nii.gz \
        81 12years end 31 M 1 54 yes /data/gcooper/movie_delay/delay_mapping/sub-81/wholebrain_delay_maps/end/pos/inny/81_end_pos_"$direction"_"$stat".nii.gz \
        82 12years end 50 M 15 35 no /data/gcooper/movie_delay/delay_mapping/sub-82/wholebrain_delay_maps/end/pos/inny/82_end_pos_"$direction"_"$stat".nii.gz \
        83 12years end 18 F 25 45 no /data/gcooper/movie_delay/delay_mapping/sub-83/wholebrain_delay_maps/end/pos/inny/83_end_pos_"$direction"_"$stat".nii.gz \
        84 12years end 22 F 60 64 yes /data/gcooper/movie_delay/delay_mapping/sub-84/wholebrain_delay_maps/end/pos/inny/84_end_pos_"$direction"_"$stat".nii.gz \
        85 12years end 23 F 22 54 yes /data/gcooper/movie_delay/delay_mapping/sub-85/wholebrain_delay_maps/end/pos/inny/85_end_pos_"$direction"_"$stat".nii.gz \
        86 12years end 19 M 63 53 no /data/gcooper/movie_delay/delay_mapping/sub-86/wholebrain_delay_maps/end/pos/inny/86_end_pos_"$direction"_"$stat".nii.gz
    done
done